import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import clsx from "clsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="flex min-h-screen flex-col items-center  w-full  p-24">
        <body
          className={clsx(`${inter.className}  grid w-full h-full`)}
        >
          <Navbar />
          <div>{children}</div>
        </body>
      </div>
    </html>
  );
}
